### ISSUE TITLE
v0.1.12 - menu for adding items/blocks to recipe grid does not open

### ISSUE THREAD

**Issue by walkerjonny** [CreativeMD/InGameConfigManager#10]
See: 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2518796-ingameconfigmanager-v0-1-12-modify-your-config?comment=189

**Comment by walkerjonny** [comment]
here is the log file:
https://gist.github.com/walkerjonny/ae2bb35735e3456e22aa

**Comment by CreativeMD** [comment]
Update to the newest CreativeCore version
