### ISSUE TITLE
Custom Texture Option

### ISSUE THREAD

**Issue by anar4732** [CreativeMD/InGameConfigManager#11]
Add Custom Texture Option for Advanced Workbench

**Comment by N247S** [comment]
Textures can always be overwritten by a resourcepack. (Even gui textures). So if you wish to change the texture of the block or gui (not sure which one you mean), you can use that option.

**Comment by CreativeMD** [comment]
Sorry, there won't be any custom textures for the advanced workbench in the near future. Maybe a 1.9 feature
