### ISSUE TITLE
issue with Latest item

### ISSUE THREAD

**Issue by Tcll** [CreativeMD/InGameConfigManager#14]
Figured I'd come here, can't paste on the forum anyways...
so I finally uploaded that image:
![Issue](https://lh3.googleusercontent.com/UdlkLpjvpk-2Yi0bkW5G8s0BuaAp6fwYD8rY25g_SnoDE39wwluA-1t2aFuUSt-6An8irbTguVvlewAuEaZJi10HIWWhixwCBRlRrst2owe7JX-MbR6llC501lZgFtTGpjsxdl1XBF8_Cq0IV8nm97U7Gnqr6kYTol0eQgkZBPI_MMVmesyGU7RcPmx6zaKEWfJ4y-0-9IBG2adYQrlxESzrNTGCInUTQjwYOokd3ID_P2mu46hsGb4rGKqU4Kys9Bco45zaYYF-9FbYdK4HtC3h9rjGnYmQGVfajqdxjXrEln0YEWKMu8Uz4aL-1of-TfojnsMY6oe3yXtXJMbpDFZmTLQeL_RHidmmAEyznx-elhN5xn_Jxsgu21mZFHRys77Oxia3jqXKTaa3KeQP_f6YFlMKfoUjbLvHgGe0crzq3x2jxd_p98ASTGt3R-tomiExDXtlmcfa8v8gXdiyIbVKVbkJ_SLo128cWNnAWF-aDARjgTWPXk18adlXkhZ-syCXaFbT8r4UzM18JvHjzgBAN7K91TAW0fSpGLCvuQ5aW1ok09wII9wbsoqK4EEWcl5e0NOCfd_YnW_YCHWY0xrLOhC_qChDIEOdEihFiEGKZqxp=w1600-no)
What's selected is the crafting table, not the certs crystal.

That's with Alpha 0.1.15 btw. ;)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/143279444857884/174353830290857)

**Comment by CreativeMD** [comment]
I'm sorry, but 1.7.10 is not supported anymore.

**Comment by Tcll** [comment]
... at the very least, fix the issue so you won't get more complaints...
it looks small enough to handle for 5 minutes...

Afterwards you can put it down and never touch it again. :)

**Comment by CreativeMD** [comment]
The problem is that it will take much much longer, because i have to setup up everything again. Due to re-installment of my computer i lost my 1.7.10 workbench :( Sorry.

**Comment by Tcll** [comment]
Ah, one of the major reasons I  quit Windows.
alright, I understand, but if you ever have the time to get back to older versions, please do. :)
