### ISSUE TITLE
Hanging While Launching A World

### ISSUE THREAD

**Issue by Cazadorsniper** [CreativeMD/InGameConfigManager#15]
The game seems to begin hanging when I try to load a world and never loads. Here is the log http://pastebin.com/unF9UiYK although i'm suspecting the issue may be with CraftTweaker. Version 1.10.2

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/143279444857884/189763700347550)

**Comment by CreativeMD** [comment]
Sorry sorry sorry, it took a way too long to answer ...
but anyway does it work if CraftTweaker isn't installed, because this crash seems to be really weird.

**Comment by Cazadorsniper** [comment]
i'll see

**Comment by Cazadorsniper** [comment]
I get this crash now: http://pastebin.com/b3hQ4UNE when i disable CraftTweaker/ModTweaker

**Comment by CreativeMD** [comment]
Not my crash, it's a crash caused by DeepResonance

**Comment by Cazadorsniper** [comment]
oh

**Comment by Cazadorsniper** [comment]
ok everything seems to work fine now (even with crafttweaker enabled) after the recent update to crafttweaker.

**Comment by Cazadorsniper** [comment]
ok after removing armorplus it stops hanging on new worlds. but this occured in the gane output log: http://pastebin.com/UBKpzmSm

**Comment by CreativeMD** [comment]
Looks like a permgen space issue. You can increase it by adding this: "-XX:MaxPermSize=256m" to the command line.

**Comment by Cazadorsniper** [comment]
its not that Curseapp/launcher automatically has that command line.

**Comment by CreativeMD** [comment]
Ok, increase it to 512m, because the crash doesn't make sense. Saying it cannot find a class although it is there.

**Comment by Cazadorsniper** [comment]
still says the same thing in the log even with the increased permsize, it seems to me that JEI doesn't recognize the advanced crafting table recipes and the recipe of the table itself.

**Comment by CreativeMD** [comment]
I will update JEI in my workbench, maybe i can fix it.

**Comment by Cazadorsniper** [comment]
okay

**Comment by CreativeMD** [comment]
tested it using jei_1.10.2-3.10.0.261 and it works without any problems, maybe try to use this version of IGCM (not released yet). Attention it will cause issues with every addon (OpticManager). https://www.dropbox.com/s/ehzy9zifmwp8v68/IGCM%20alpha%20v1.0.4%20mc1.10.zip?dl=0

**Comment by Cazadorsniper** [comment]
can you try this version jei_1.10.2-3.12.6.304 that might be why.

**Comment by CreativeMD** [comment]
Yep, ok that causes a lot of issue (didn't see that version), working on a fix and will release it soon.

**Comment by CreativeMD** [comment]
Fix is released, thanks for reporting this issue.
