### ISSUE TITLE
Crashes ?

### ISSUE THREAD

**Issue by ghost** [CreativeMD/InGameConfigManager#16]
it crashes on Minecraft 1.11.2. I installed creative core 1.7.0.
[crash-2017-03-19_10.28.20-client.txt](https://github.com/CreativeMD/IGCM/files/853088/crash-2017-03-19_10.28.20-client.txt)

**Comment by ghost** [comment]
ohhh... it works with InGameConfigManager mod. But you put it on "Optional Mods" section :D ...

**Comment by ghost** [comment]
oh... this is IGCM's github... but i clicked the issues tab on OpticManager mod xD

**Comment by CreativeMD** [comment]
Ok, thanks for reporting. Fixed it. IGCM is now a required library and the links should work just fine.

**Comment by ghost** [comment]
thank you too..
