### ISSUE TITLE
Recipe Problem/Bug

### ISSUE THREAD

**Issue by ghost** [CreativeMD/InGameConfigManager#18]
i am using convenient additions mod, and there is adventurer's pickaxe in that mod. adventurer's pickaxe can be repaired by it is material, for example you can repair your iron adventurer's pickaxe with an iron ingot in shapeless crafting. but when i install igcm, i can not repair my adventurer's pickaxe, no output/result on crafting. please help. thanks
https://github.com/Necr0/ConvenientAdditions/issues/20

**Comment by QbDesu** [comment]
@CreativeMD I don't know how your mod operates, so I don't know about this one. The recipe in question is just a custom implementation of IRecipe. Is there something I should look after to make sure my mod's compatibility with yours?

**Comment by CreativeMD** [comment]
I might have an idea what could cause the issue. IGCM tries to give every recipe a unique key, so the client knows what the server means and the other way round. If IGCM is not able to read either the input nor the output, the key of the recipe won't be unique, which can cause some issues. I will think about a way to fix it.

**Comment by kenijey** [comment]
i really need help about it.. i think igcm causes more recipe bugs on other mods' unique recipes as like this one. please help... thanks

**Comment by ghost** [comment]
still waiting :(

**Comment by ghost** [comment]
still waiting :((

**Comment by CreativeMD** [comment]
Does this fix the problem?
https://www.dropbox.com/s/qbrrjr87dw5w7nw/IGCM%20beta%20v1.1.0%20mc1.11.2.zip?dl=1

**Comment by ghost** [comment]
hey ah, i just tried that version but it caused [this](https://github.com/CreativeMD/IGCM/issues/17) problem again such as before. :(

**Comment by ghost** [comment]
oh sorry, it is happening without IGCM too. let me check what's  causing this, then try this bug fix.

**Comment by ghost** [comment]
okay, i solved my bug (can't load/create world). Tried your new version of IGCM, and adventurer's pickaxe bug solved. thank you so much!! we love you :D !
