### ISSUE TITLE
Itemstack acts as a recipe requirement but does not consume above 1 item.

### ISSUE THREAD

**Issue by willabusta** [CreativeMD/InGameConfigManager#2]
![2015-09-21_21 45 27](https://cloud.githubusercontent.com/assets/6618634/10009470/7f2034e8-60ab-11e5-9748-b4517cb2ce2a.png)
![2015-09-21_21 45 50](https://cloud.githubusercontent.com/assets/6618634/10009472/7f253f56-60ab-11e5-8e91-4122031f4ae4.png)
![2015-09-21_21 45 55](https://cloud.githubusercontent.com/assets/6618634/10009471/7f252d5e-60ab-11e5-9195-ff93c80bdf74.png)

**Comment by CreativeMD** [comment]
Yes, i forgot about this problem. It is impossible to change this vanilla behavior (including supporting mods). I will remove this stacksize feature in the next version.

**Comment by crunkazcanbe** [comment]
Could you just make this feature work ? I would love to have a feature like this working !

**Comment by N247S** [comment]
We could make this work, for vanilla craftingBenches. Though the main problem is that it wont work for other (added) craftingBenches. Thats

**Comment by CreativeMD** [comment]
It will be available for other machines, example: my RA machines (they will get supported soon).

**Comment by crunkazcanbe** [comment]
Yeah i would love this feature to stay in the mod . This can be very useful for mod pack makers and thats what i was going to use it for .

**Comment by CreativeMD** [comment]
Yep, it will only be disabled if it's not possible (workbench and furnace)

**Comment by willabusta** [comment]
OH YES! yes yes yes creativemd! thats all I've ever wanted!!!
