### ISSUE TITLE
Incredible Bug

### ISSUE THREAD

**Issue by ghost** [CreativeMD/InGameConfigManager#20]
latest version of igcm kills the Json recipe edit mod. it kills all my custom recipes that doesn't work **on dedicated server side**. please help :(
in single player it works fine, but when i install it on dedicated server, all my custom recipes won't work :( i'm clicking the result item on crafting but it doesn't give the result item to me...

**Comment by CreativeMD** [comment]
Yeah someone else also reported this issue. I will to some testing. Hopefully i can find the cause.

**Comment by ghost** [comment]
yes we hope too. we are waiting for a fix for it. get luck with. thanks ^^

**Comment by ghost** [comment]
and this bug wasn't happening in the second latest version of IGCM.

**Comment by CreativeMD** [comment]
which one? beta 1.0.0?

**Comment by ghost** [comment]
Yes that is.

**Comment by CreativeMD** [comment]
Do those versions fix it?
https://www.dropbox.com/s/yuv22quf7g9qzq5/CreativeCore%20v1.7.1%20mc1.11.2.jar?dl=1
https://www.dropbox.com/s/poagxvxryevw5t9/IGCM%20beta%20v1.1.1%20mc1.11.2.zip?dl=1

**Comment by ghost** [comment]
sorry, i just felt sleep :D trying it right now.

**Comment by ghost** [comment]
ah, no. they don't :( still happening. should i have deleted old config before trying it? i didn't.

**Comment by CreativeMD** [comment]
I couldn't reproduce it, everything works perfectly fine on my end. I started a dedicated server, joined with two clients. Opened 'add crafting table recipe' on both clients. Added a random recipe, hit 'save' and it immediately updates for both clients. I can craft the recipe and it's still there after restarting the server.

Using Forge 13.20.0.2279
IGCM v1.1.1
CreativeCore v1.7.1

Could you record it or maybe share some screenshots?

**Comment by ghost** [comment]
oh no, i'm using json recipe edit mod, i'm talking about it. igcm kills the custom recipes of that mod made by ezterry. i'm using that mod because i'm using it also for initial inventory setup. this is why i'm not deleting that mod and making custom recipes with using IGCM.

**Comment by CreativeMD** [comment]
oh ... that's something completely different :D yeah i cannot help there. If recipes will be added too late to the game, igcm will not recognize them. There is nothing i can do about it, sorry.

**Comment by ghost** [comment]
oh :( it is so bad. if i use IGCM instead of Json Recipe Edit mod to make recipes, i can not make my initial inventory setup. i'm very confused :(... what should i do...

**Comment by ghost** [comment]
but it was working on IGCM beta 1.0.0 ... :(

**Comment by CreativeMD** [comment]
No idea, never used Json Recipe Edit mod, but from my point of view, the only problem is that IGCM will ignore recipe added by this mod. No idea why inventory setup shouldn't work. Maybe contact the author?

**Comment by ghost** [comment]
oh wait, initial inventory setup works :D then i will use Json Recipe Edit and IGCM together again. I will try to make all my recipes in IGCM, hope all of them work. (shaped, shapeless, delete recipe, result count etc)

**Comment by CreativeMD** [comment]
It should :D

**Comment by ghost** [comment]
omg, my game has been crashed when try to make a recipe. :( 
[crash-2017-04-09_14.02.00-client.txt](https://github.com/CreativeMD/IGCM/files/908141/crash-2017-04-09_14.02.00-client.txt)
edit: i was trying to make a recipe for an another mods item.

**Comment by ghost** [comment]
aaaand i got it not crashing wit deleting my recipes from Json Recipe Edit mod. :D

**Comment by ghost** [comment]
ahhh, i found another bug. let me open new issue.
