### ISSUE TITLE
Keyboard Keys Works As Normal While Typing In Search Box

### ISSUE THREAD

**Issue by ghost** [CreativeMD/InGameConfigManager#21]
what i did: i open IGCM GUI, clicked Crafting Table, clicked Crafting Table Disable, then clicked the search box, typed something and at the end i see my inventory open :D i think it happened because i pressed 'E'. So i can't search items properly. thanks for work for fix from now...

**Comment by kenijey** [comment]
and ah, i need help about meta data. i want to make a recipe from wool, but i can put only white wool, but i want it include all colored wools (wool, *). How can i do this? How can i put wool with all meta data types in 1 slot on crafting? thanks...

**Comment by kenijey** [comment]
and another bug: there is an item in BloodMagic mod called Mining Regent, it is code is this: bloodmagic:itemcomponent, 3. 3 is its metadata and when i select it, IGCM selects automatically metadata as 0, but metadata 0 one is another item so i can not select that item. IGCM needs a feature that lets user configure metadata.

**Comment by kenijey** [comment]
and i need help about something, how can i include all metadatas of an item in one slot? for example all colored wool types in crafting being used to craft something.

**Comment by CreativeMD** [comment]
This should fix it:
https://www.dropbox.com/s/tnsrhlyb0irt4ep/CreativeCore%20v1.7.2%20mc1.11.2.jar?dl=1
