### ISSUE TITLE
IGCM kills the recipes of Abyssal Craft mod

### ISSUE THREAD

**Issue by ghost** [CreativeMD/InGameConfigManager#23]
in abyssal craft mod, there are upgrade kits, whic are used to upgrade any tool to greater material (for example cobblestone upgrade kit + wooden pickaxe on shapeless crafting=stone pickaxe) please help it. thanks..
using forge 2282, IGCM 1.1.1, abyssal craft 1.9.4-pre-2

**Comment by CreativeMD** [comment]
I could not reproduce this in this way. Could you give me an example? I tested some recipes, but those were working just fine.

**Comment by ghost** [comment]
omg, sorry it is not about igcm.

**Comment by CreativeMD** [comment]
Oh ok :D
