### ISSUE TITLE
Wrong mcmod.info file

### ISSUE THREAD

**Issue by canitzp** [CreativeMD/InGameConfigManager#24]
I took a look into the mcmod.info file at this repository and the one inside the latest mod version and they are different one. I noticed this cause my self made modpack launcher couldn't detect the mod version. Since the gradle files of the project aren't at the repo, I can't take a look into them to see if there goes something wrong.
Since this isn't a minor issue I would understand if you don't fix it for now.

**Comment by CreativeMD** [comment]
Thanks for reporting will be fixed in v1.1.2.
