### ISSUE TITLE
Any player can edit recipes on server

### ISSUE THREAD

**Issue by DennHenda** [CreativeMD/InGameConfigManager#25]
I'm running a small private server, I'm able to log in as a regular player (not op) and change/add any recipe. The new and disabled recipes work as desired, it's just the IGCM gui is available to anyone.
Thanks

Forge1.11.2 build 2282
igcm 1.1.2
Creative core 1.7.3

**Comment by CreativeMD** [comment]
Can they use the command /ConfigManager or do they use the key instead?

**Comment by DennHenda** [comment]
Definitely able to use the key, unsure about the command. I'm at work, but I can test this when I get home.

**Comment by DennHenda** [comment]
The command cannot be used, it says you do not have permission. The V key works at any time.

I also tested as an op and they both work.

**Comment by CreativeMD** [comment]
Should be fixed now. Thanks for reporting this issue.

**Comment by DennHenda** [comment]
Having another problem with the keybind - I'll create a new issue.
Thanks for working on this, by the way. Your mods are definitely appreciated by me!

**Comment by DennHenda** [comment]
Sorry, after poking around with it a bit more, it seems to work.  Don't know what the issue was, but it crashed a couple times when hitting V while connected to the server.
I tested on single player and it worked, then after that it worked perfect on the server.
Thanks again, love the mod!

**Comment by CreativeMD** [comment]
Maybe send me the crash-log?

**Comment by DennHenda** [comment]
I don't know what the circumstances are, but it does happen every once in awhile if I accidently hit "V" while on the server.
https://pastebin.com/CrnqPjza

**Comment by CreativeMD** [comment]
Does this fix it?
https://www.dropbox.com/s/8p4l142zg4xnvx7/IGCM%20v1.1.4%20mc1.11.2.zip?dl=1

**Comment by DennHenda** [comment]
No, still same issue. I updated both the server and client.
https://pastebin.com/uzcMvGpb

**Comment by CreativeMD** [comment]
Does this fixes it?
https://www.dropbox.com/s/8p4l142zg4xnvx7/IGCM%20v1.1.4%20mc1.11.2.zip?dl=1

**Comment by CreativeMD** [comment]
Should be fixed (v1.1.4 should be available soon).

**Comment by DennHenda** [comment]
Just confirming that this is fixed. Thanks
