### ISSUE TITLE
JEI compatibility

### ISSUE THREAD

**Issue by POKFX45** [CreativeMD/InGameConfigManager#26]
Hi, would be great if you add JEI compatibility for the advanced workbench, and if it also retains its inventory! Great mod so far!

**Comment by CreativeMD** [comment]
Ok? It's implemented already, or are you talking about something else?
![](http://i.imgur.com/cjAYujd.png)

**Comment by POKFX45** [comment]
Nope, but it seems to not work for me... :\ I will investigate more and I'll let you know

**Comment by CreativeMD** [comment]
Which versions do you use?

**Comment by CreativeMD** [comment]
Are you using 1.10.2 or 1.11.2?

**Comment by CreativeMD** [comment]
Issue will be closed due to inactivity.
