### ISSUE TITLE
[1.1.3] Crash on opening GUI

### ISSUE THREAD

**Issue by Aphyxia** [CreativeMD/InGameConfigManager#27]
Crash when press the key to open the GUI in server as op. Untested elsewhere. Worked with version 1.1.1.
Crashlog:
https://pastebin.com/hvE0mVf8

**Comment by CreativeMD** [comment]
Does this fixes it?
https://www.dropbox.com/s/8p4l142zg4xnvx7/IGCM%20v1.1.4%20mc1.11.2.zip?dl=1

**Comment by Aphyxia** [comment]
This makes the GUI opening button not do anything. Tried changing it to something else but still does nothing. Also tested in single-player. Same thing.

**Comment by Aphyxia** [comment]
Found this in the logs, possibly related: 
https://pastebin.com/S3iHwQzC

**Comment by CreativeMD** [comment]
Oh damn, made a small mistakes, just redownload the file. It should work now.

**Comment by Aphyxia** [comment]
Now getting `[13:55:23] [Netty Server IO #1/INFO]: [STDOUT]: Invalid packet id=`

**Comment by CreativeMD** [comment]
download it again ... :D sorry i always forget something

**Comment by Aphyxia** [comment]
No worries, the responses are quick and this last change seems to have fixed it. Works in both server and single-player. Thanks.

**Comment by CreativeMD** [comment]
Nice will release it soon.
