### ISSUE TITLE
crash when opening ui for adding recipes on server(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [CreativeMD/InGameConfigManager#28]
forge:1.112-2285
ccore:CreativeCore v1.7.3 mc1.11.2
ingamecfg: IGCM v1.1.3 mc1.11.2

[crash-2017-04-30_21.10.20-client.txt](https://github.com/CreativeMD/IGCM/files/966799/crash-2017-04-30_21.10.20-client.txt)

**Comment by CreativeMD** [comment]
It is fixed in IGCM v1.1.4.
