### ISSUE TITLE
Game Freezes When I Try To Open IGCM GUI With My Old Config

### ISSUE THREAD

**Issue by ghost** [CreativeMD/InGameConfigManager#29]
same as here https://github.com/CreativeMD/ItemPhysic/issues/39
you can reproduce it with installing my IGCM config (.nbt) https://drive.google.com/open?id=0B6b0yPfoStOGb1NZdkRZbjEyZkk

**Comment by ghost** [comment]
i think newest version of igcm killed my .nbt recipes contained file =(((

**Comment by ghost** [comment]
well, i remade all recipes from zero.

**Comment by CreativeMD** [comment]
Hey, finally found some time to look at it. The issue is caused by an invalid InfoBlock. I think you have used a block in a recipe, but later on removed the mod. I will release a fix for this, but resetting the config does also work. Sorry that it took me so long.

**Comment by ghost** [comment]
thank you for dealing with this.

**Comment by ghost** [comment]
please look at the opticmanager issue, it's very important. :/

**Comment by CreativeMD** [comment]
Yes, i will do. BTW the newest CreativeCore version (v1.7.4) should fix it.

**Comment by ghost** [comment]
fix what? this issue we are talking on?

**Comment by CreativeMD** [comment]
That one of course :D

**Comment by ghost** [comment]
thx :)
