### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Tsyklop** [CreativeMD/InGameConfigManager#3]
Crash: http://pastebin.com/eZhxb7Bf

InGameConfigManager Alpha v0.1.1, CreativeCore 1.3.9, Forge 1492, Forge 1517

**Comment by CreativeMD** [comment]
Could you give me the name of the mod files?

**Comment by Tsyklop** [comment]
I found what the error was. I put mod CreativeCore in a folder "1.7.10". Move the mod in a folder mods, and it worked.

Could you make so that CreativeCore could lay down a folder 1.7.10?

**Comment by CreativeMD** [comment]
I don't know what causes this problem, i tested it and there is no issue at all.

**Comment by Tsyklop** [comment]
http://pastebin.com/tHAcrPje

**Comment by CreativeMD** [comment]
Yes :D
but could you please "zip" and upload them?

**Comment by Tsyklop** [comment]
Put all of mods in the "zip"? and upload?

**Comment by Tsyklop** [comment]
@CreativeMD https://drive.google.com/file/d/0B9c2x-D6eUzeMEdEQ1NTQktyMEk/view?usp=sharing

**Comment by CreativeMD** [comment]
Thanks :D

**Comment by Tsyklop** [comment]
When I moved Cre4ativeCore to the folder "mods" he worked ..

**Comment by CreativeMD** [comment]
Wait, when did it crash?
1. CreativeCore is in mods/
2. CreativeCore is in mods/1.7.10

**Comment by Tsyklop** [comment]
2. CreativeCore is in mods/1.7.10

**Comment by CreativeMD** [comment]
Oh, yes it has to be in the mods folder :D
This is not really an issue, but anyway i will try to fix the World Generation Manager issue.

**Comment by Tsyklop** [comment]
I would like that he was in mods / 1.7.10. There I found most libraries.

**Comment by CreativeMD** [comment]
Yes, but it's not a library but a mod.

**Comment by Tsyklop** [comment]
Okay. Thx

**Comment by SvEgiiVEteR** [comment]
on server.
http://pastebin.com/iNjwX5ss
