### ISSUE TITLE
Error in Logs

### ISSUE THREAD

**Issue by ghost** [CreativeMD/InGameConfigManager#30]
![12](https://cloud.githubusercontent.com/assets/24831406/26513232/1ba9c0ea-4273-11e7-9665-aadae3119818.PNG)
[fml-client-latest.log.txt](https://github.com/CreativeMD/IGCM/files/1033005/fml-client-latest.log.txt)
forge 2304 latest igcm / jei for 1.11.2

**Comment by ghost** [comment]
and plz tell me if i should report it to JEI.

**Comment by CreativeMD** [comment]
Are you using the newest JEI version where the added recipes are not shown?

**Comment by ghost** [comment]
it was jei_1.11.2-4.3.6.280.jar
so, sorry :D

**Comment by CreativeMD** [comment]
No problem, could do me a favor and reopen this issue, once the new jei version is out of the beta?

**Comment by ghost** [comment]
uhm, i just installed JEI b282, and i will check it for you soon.

**Comment by ghost** [comment]
![12](https://cloud.githubusercontent.com/assets/24831406/26528459/fd126360-43b4-11e7-8c3c-206ccc41d1cd.PNG)
this is with jei b282. just now.

**Comment by CreativeMD** [comment]
Nevermind, as i said i will update it once the new version is out of the beta phase.
