### ISSUE TITLE
[1.12] Will there be custom crafting recipes?

### ISSUE THREAD

**Issue by NovaViper** [CreativeMD/InGameConfigManager#31]
This is the main feature that's holding me back from switching completely over to 1.12 on my server (most of my mods have updated to 1.12). I have a combination of mods that have extremely difficult recipes for my friends, nieces and nephews. I hope that this feature comes back

**Comment by CreativeMD** [comment]
Unfortunately it does not look like it is possible. Forge changed how recipes work, so i cannot modify them while the game is running, since it would cause several issues :(.

**Comment by NovaViper** [comment]
Awh.. what about something that you can edit in a json? Or even create a separate program that you can edit recipes in the menu, then have it upload to Minecraft?

**Comment by CreativeMD** [comment]
I'm not really into it to be honest. Maybe there is another way for IGCM to modify the recipe list, i will give it another try rather soon, but i need to do some other stuff first.

**Comment by NovaViper** [comment]
Ok! If you need any help, I can try my best to contribute to the code in case I find anything 'interesting' ^^

**Comment by CreativeMD** [comment]
Sounds great :D I will let you know once i got some news.

**Comment by NovaViper** [comment]
Thanks ^^

**Comment by CreativeMD** [comment]
Hey there,
you probably don't remember this here, but I readded the crafting table in the newest IGCM version for 1.12.2.

Finally! It might be rather buggy, but it's working in theory.
