### ISSUE TITLE
Game crashes on world gen

### ISSUE THREAD

**Issue by sharkck** [CreativeMD/InGameConfigManager#33]
The client loads without any issues.  When I hit create new world, I get the following crash:
[crash-2017-07-28_19.45.33-server.txt](https://github.com/CreativeMD/IGCM/files/1184478/crash-2017-07-28_19.45.33-server.txt)

Even after reloading the client, it still crashes when trying to load up the world:
[crash-2017-07-28_19.49.48-server.txt](https://github.com/CreativeMD/IGCM/files/1184480/crash-2017-07-28_19.49.48-server.txt)

**Comment by CreativeMD** [comment]
That's an issue with TickDynamic and has been reported already here: https://github.com/CreativeMD/CreativeCore/issues/20
