### ISSUE TITLE
[1.11.2] Crafting crash

### ISSUE THREAD

**Issue by lena-kze** [CreativeMD/InGameConfigManager#34]
Issue with IC2.

ic2 version: industrialcraft-2-2.7.81-ex111.jar

[fml-client-3.log](https://github.com/CreativeMD/IGCM/files/1522041/fml-client-3.log)

**Comment by CreativeMD** [comment]
Sorry for my later response, does this version fixes it?
https://www.dropbox.com/s/6fw0lnc47mgz1wg/IGCM%20v1.1.7%20mc1.11.2.jar?dl=1

**Comment by lena-kze** [comment]
Seems to work, i'll test it on server later today.

Scheint zu funktionieren, ich werds heute Abend mal auf dem Server probieren.

**Comment by lena-kze** [comment]
So I tested it on the server.

The game no longer crashes when crafting a vanilla block of iron. (tested example)
The game does crash when trying to craft ic2 items.

[fml-client-latest.log](https://github.com/CreativeMD/IGCM/files/1528480/fml-client-latest.log)
[latest.log](https://github.com/CreativeMD/IGCM/files/1528473/latest.log)

_Nullpointer klingt ja super. #erstes Semester :)_

**Comment by CreativeMD** [comment]
Ok, but this is not an issue of IGCM, you should report it to IC2.


NullPointerException will be thrown if an object is ```null``` but you try to do something with it.
For example:
```recipe.getRecipeOutput();``` -> ```null.getRecipeOutput```
getRecipeOutput() cannot be called, since the object does not exist.
