### ISSUE TITLE
JEI Doesn't Catch IGCM Modified Recipes

### ISSUE THREAD

**Issue by ghost** [CreativeMD/InGameConfigManager#36]
i disabled a recipe from other mod, then did new recipe. on the crafting table, it works. but in JEI, i still see the old recipe. dunno why...
using IGCM_v1.2.0pre-4_mc1.12.2
using jei_1.12.2-4.8.5.159
Forge 2654...
logs....
[latest.log](https://github.com/CreativeMD/IGCM/files/1876528/latest.log)
[debug.log](https://github.com/CreativeMD/IGCM/files/1876529/debug.log)

**Comment by ghost** [comment]
i don't know should i report to @mezz

**Comment by ghost** [comment]
really, no reaction on this issue?

**Comment by CreativeMD** [comment]
There is no support for it at the moment, I tried to readd it, but there are several problems. I will continue tomorrow, maybe I can fix it.

**Comment by ghost** [comment]
oh, good! thank you CreativeMD. i'm waiting hopefully.

**Comment by CreativeMD** [comment]
Does this one work?
https://www.dropbox.com/s/cisnqfqr4rd6oqg/IGCM_v1.2.0-pre5_mc1.12.2.jar?dl=1

**Comment by ghost** [comment]
uhm, i'm working on it for 30 mins, if i put this build of IGCM you shared into my modpack, i can't create new world. it errors at the end with java.io something. right now i replaced with old version(latest on curse) of IGCM, i could create new world. so i cant create new world with this. :(

**Comment by CreativeMD** [comment]
Can you send me the log?

**Comment by ghost** [comment]
wait, should i delete old IGCM configs? cus i didn't

**Comment by ghost** [comment]
[latest.log](https://github.com/CreativeMD/IGCM/files/1886397/latest.log)
[debug.log](https://github.com/CreativeMD/IGCM/files/1886398/debug.log)
and here are the logs that i can't create a new world (tried superflat&creative mode on)
**and it returns back to the server list (multiplayer tab)**

**Comment by ghost** [comment]
and ah, i tried it with vanilla (IGCM pre5 + JEI + creative core) then made some recipies, it works. but in my modpack :( i can't create new world.

**Comment by ghost** [comment]
the error is this actually(when i try to create new world):
![asd](https://user-images.githubusercontent.com/24831406/38458571-649eaf4e-3aa8-11e8-9060-8d27a91c0950.PNG)

**Comment by ghost** [comment]
btw, i can't load any world too. tried my old world, same error..

**Comment by CreativeMD** [comment]
I will try to find a different way to do this.

**Comment by ghost** [comment]
thanks a lot! waiting hopefully. get luck with.

**Comment by ghost** [comment]
still waiting hopefully... :(

**Comment by ghost** [comment]
you there? :D i know i'm borring but we really need its fix :(

**Comment by CreativeMD** [comment]
I'm really sorry, but at the moment there are too many other things ... I have to contact the author of JEI and hope he will help me to find a good solution for it. Unfortunately, I don't have enough energy and time to do that at the moment.

**Comment by CreativeMD** [comment]
I contacted the author: https://github.com/mezz/JustEnoughItems/issues/1217

**Comment by ghost** [comment]
oh, i'm very happy now! hope he will help and it gets fixed. waiting so hopefully..

**Comment by ghost** [comment]
hey, did mezz's help work? just wondering how is it going :( i'm very hoping it be fixed.

**Comment by CreativeMD** [comment]
I'm on it, things just take time, unfortunately I also got other stuff to do.

**Comment by ghost** [comment]
shall i pray for you? xD

**Comment by CreativeMD** [comment]
Still waiting for the response of mezz.

**Comment by ghost** [comment]
appreciate you man, you do great work as always. was just trying to make you smile:D

**Comment by ghost** [comment]
hey creativemd, can you build a special version of igcm for me? that loads custom recipies at the game start, not in the game. i don't want to use other specific mods that adds recipies such like craft tweaker. i mean, can you build a version that loads my recipies at game start (also) so after i restart the game, i can see the recipies. is it possible? i just need it at the moment, and until it's fixed, i can use it :3 thanks.

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. I can't do that, but I can send you the current pre-release which has duplicates in it, but everything else works fine: https://cdn.discordapp.com/attachments/276752435869908993/455706245152768000/IGCM_v1.2.0-pre6_mc1.12.2.jar

**Comment by ghost** [comment]
wow! gonna try it. thanks a lot, hope it won't crash with anything xD

**Comment by ghost** [comment]
response(feedback): YES!!!!! IT WORKS!!!!!!!! thank you :D no even any crash. i think you can close this issue.

**Comment by CreativeMD** [comment]
No, the duplication issue is still a problem, it will cause memory leaks ...

**Comment by CreativeMD** [comment]
Hey can you do some testing for me? Hit F3 and remember how much RAM you are using. Then go to the config menu (of IGCM), go to crafting table and hit save several times. Then check how much RAM you are using afterwards. I have to know how serious this memory issue is.

**Comment by ghost** [comment]
okay! i will do this today. and tell you does it leaks memory that much..

**Comment by ghost** [comment]
btw, mezz just released a new version of JEI that says in changelog: "Fix support for adding/hiding recipes at runtime" .
is this what we needed? xD

**Comment by CreativeMD** [comment]
Partially, can you try it with the old version of jei first?

**Comment by ghost** [comment]
try what and which version of JEI? b198 ?

**Comment by CreativeMD** [comment]
just don't update, before you do the thing I asked you above.

**Comment by ghost** [comment]
well i did the test, it crashed actually.
i'm using VanillaFix mod that saves me after a crash (lets me play if crash is not too bad)
and i think after de 2nd or 3rd click (on the save button) it crashed properly on every click..
[crash-2018-06-14_13.56.25-client.txt](https://github.com/CreativeMD/IGCM/files/2101977/crash-2018-06-14_13.56.25-client.txt)
here is the latest crash report, i have 6, can upload if u wish.

**Comment by ghost** [comment]
what do i do now? do you want me to update jei or something? i can help

**Comment by CreativeMD** [comment]
Just update and everything should work fine, I will try to find out why this crash occurs, but that's not related to this issue. Finally I can close it and call it done.
