### ISSUE TITLE
Mod Dependency

### ISSUE THREAD

**Issue by ghost** [CreativeMD/InGameConfigManager#37]
I mean CreativeCore; game just crashes if it isn't installed. You had better to add mod dependency that will provide the game will tell the player this mod requires CreativeCore to run instead of crashing. It would be nice...

**Comment by CreativeMD** [comment]
Will be part of the next version. Thanks for bringing this to my attention!

**Comment by ghost** [comment]
thank you too. i'm just scared a bit cus of disturbing you with github emails too much xD

**Comment by CreativeMD** [comment]
No problem, just keep doing that, those things are important.
