### ISSUE TITLE
Conflict with CraftTweaker Recipes.

### ISSUE THREAD

**Issue by Rsslone** [CreativeMD/InGameConfigManager#39]
I have crafttweaker with scripts, I added this mod for the opticsmanager but this mod seems to be effecting my crafttweaker recipes. The recipes are gone from the JEI as if they don't exist and when I view them in the IGCM it shows a blank table (See image)

https://i.imgur.com/aTZmfwJ.png

**Comment by CreativeMD** [comment]
Yes there are some issues with. I would highly recommend to add the recipes using igcm. I will try to fix it anyway, but it will most likely take some time.

**Comment by Rsslone** [comment]
Could it be easier if you added a config option to disable the crafting as a module?

**Comment by CreativeMD** [comment]
Can you try out this version?
https://www.dropbox.com/s/x0wexktss2wx4e4/IGCM_v1.2.2_mc1.12.2.jar?dl=1

**Comment by Rsslone** [comment]
I can confirm that this fixes the issue. Thanks a bunch!
p.s. might want to note that config as a compat config for crafttweaker

**Comment by Rsslone** [comment]
Okay so the furnace needs to be disabled as well. Its causing all of my furnace recipes from functioning.

**Comment by CreativeMD** [comment]
Ok uploaded it to curseforge, should be available soon:
https://minecraft.curseforge.com/projects/ingameconfigmanager/files/2595704
