### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by SvEgiiVEteR** [CreativeMD/InGameConfigManager#4]
on server.
http://pastebin.com/iNjwX5ss
CreativeCore v1.3.9 mc1.7.10.jar
InGameConfigManager Alpha v0.1.2 mc1.7.10.zip

**Comment by CreativeMD** [comment]
It's fixed in 0.1.3

**Comment by SvEgiiVEteR** [comment]
http://pastebin.com/yt4e83YG
updated, but when you connect such an error in the client. and not let the server.
before there was such a ...

**Comment by CreativeMD** [comment]
Just redownload the newest versio, it's fixed.

**Comment by SvEgiiVEteR** [comment]
Thank you, all is good!
