### ISSUE TITLE
Just a heads up due to the new updates.

### ISSUE THREAD

**Issue by Rsslone** [CreativeMD/InGameConfigManager#41]
I figured this one out myself but if there is a config mismatch it will throw an unclear "fatal error". Just in case you get reports for something like this I wanted to give you a heads up. You may close this anytime as its a non-issue.
https://gist.github.com/Rsslone/493fb36bf36c31ca666a373b5783070c

**Comment by CreativeMD** [comment]
I will add a comment to the option to make it more obivous
