### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by phyne** [CreativeMD/InGameConfigManager#42]
After noticing
`> Sep 14, 2018 11:45:10 AM io.netty.util.ResourceLeakDetector reportTracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.`
popping up in my console very occasionally, I decided to visit the link and enable advanced leak reporting as specified on the page.

This is the resulting log for when a leak happened again: https://pastebin.com/raw/e8hjYm2L

I only see IGCM and your core mod referenced in the reported leak. Forgive me if your mod is not the issue, but I ultimately do not understand what is happening. When my server is left up for many, many hours, the performance starts to degrade heavily.

My complete mod list if needed: https://pastebin.com/raw/JfAAuG36

Edit: Interestingly enough, I noticed that I am a version behind although I downloaded your mod after August 24th, as well as being behind on CreativeCore. I guess you'll tell me to update to the latest and see if the problem reoccurs?

**Comment by CreativeMD** [comment]
That's a known issue, already tried to find out why it is there, but I couldn't fix it. To make it short it's not an issue. There is no memory leak (at least no noticeable one). Thanks for taking the time and reporting this issue anyway!

**Comment by phyne** [comment]
I guess I underestimated the impact of 130+ mods on the server performance if the leak is indeed not causing any actual issues. Thanks for getting back quickly. Love all your mods man!

**Comment by CreativeMD** [comment]
You can test it with only CreativeCore and LittleTiles installed. I never saw anything suspicious.

**Comment by phyne** [comment]
Ok, I might set up a test server to try and weed out performance issues. I generally don't have any other blatant errors getting thrown around in the console/logs, which is why I assumed it was the thing that said "SEVERE: LEAK" :) It was something that didn't start happening until many days of running the server as well.

In the end I just run regular restarts, which is something that can probably be done anyway.

**Comment by CreativeMD** [comment]
Feel free to share your results, I would love to see how it performs.
