### ISSUE TITLE
Crash With Tough Expansion

### ISSUE THREAD

**Issue by KenyMylankca** [CreativeMD/InGameConfigManager#45]
PLEASE, please help [**this**](https://github.com/p455w0rd/ToughExpansion/issues/37). thanks!

**Comment by CreativeMD** [comment]
That is a familiar issue, I will try to fix it.

**Comment by CreativeMD** [comment]
Your issue should be fixed in v.1.2.6, which will be available soon (already uploaded it).

**Comment by KenyMylankca** [comment]
Yes, it fixed.
