### ISSUE TITLE
CraftTweaker

### ISSUE THREAD

**Issue by corgiblu** [CreativeMD/InGameConfigManager#46]
Ok. So this is apparently conflicting with craftweaker making it so none of the recipes that are added are showing in JEI.

I have no idea how to fix it other than remove the mod, and no I can't just use IGCM for the recipes as I have already added many many recipes with CT.

I guess I won't be able to use itemphysic full if this can't be fixed. Because I need IGCM to make it so everything can burn in lava/fire.

**Comment by CreativeMD** [comment]
You can disable the workbench feature in the config file, this should fix the incompatibility.

**Comment by corgiblu** [comment]
That's great! I'll check it out later. Thanks!

**Comment by corgiblu** [comment]
Ok. Well that fixed the CT issue, but apparently it is also your mod that adds an annoying "Switch" button to the crafting table when trying to craft a conflicting recipe. That would be fine since I'm fixing conflicts by hand but some don't need to be fixed. Like apparently making a stone pickaxe results in 2 outputs. They're both stone pickaxes though. So if I could disable that feature it'd be great otherwise i'll have to do what  I was going to do originally. Disable this and itemphysic.

**Comment by CreativeMD** [comment]
Will be added to the newest IGCM version v1.2.7, which will be available soon.
