### ISSUE TITLE
[Crash] Issue with either the Presents mod or IGCM

### ISSUE THREAD

**Issue by DWX12** [CreativeMD/InGameConfigManager#47]
Got a crash the moment I tried using a CraftingTweaks button in a vanilla crafting table to spread items across the grid:

https://paste.dimdev.org/lepufarebu.mccrash

It suspects that either the Presents mod or IGCM caused the crash. Not sure what's happening though.

**Comment by CreativeMD** [comment]
Have you reported it to the presents mod as well?

**Comment by DWX12** [comment]
I believe I did on their page. With all the recent versions, the issue hasn't come back. I will close this and will inform the proper people if it comes up again. Thanks.
