### ISSUE TITLE
Crash while using forge and creativecore

### ISSUE THREAD

**Issue by thisaray** [CreativeMD/InGameConfigManager#48]
[latest.log](https://github.com/CreativeMD/IGCM/files/2739008/latest.log)
only creativecore and IGCM installed, creative core only works just fine

**Comment by CreativeMD** [comment]
Try out a different forge version, maybe 2779? I will try to update it to the newer forge versions soon.

**Comment by thisaray** [comment]
Still crashing on 2779, even on 2486

**Comment by rvveber** [comment]
works fine with 2795 and 2768. Tested on client and Server.
I see you have the default quite old minecraft-pre-delivered  java version, consider updating it please and set the path to your new jre/bin folder in the launcher.

**Comment by thisaray** [comment]
> works fine with 2795 and 2768. Tested on client and Server.
> I see you have the default quite old minecraft-pre-delivered java version, consider updating it please and set the path to your new jre/bin folder in the launcher.

Okay, tried it with 2807 and  1.8.0_181, still crashing! [latest.log](https://github.com/CreativeMD/IGCM/files/2748656/latest.log)

**Comment by thisaray** [comment]
here is another log with forge 2745
[latest.log](https://github.com/CreativeMD/IGCM/files/2748736/latest.log)

**Comment by CreativeMD** [comment]
You are using CreativeCore for 1.11.2, you have to use the version for 1.12.2.

**Comment by CreativeMD** [comment]
Same issue here, please update to CreativeCore 1.12.2.
