### ISSUE TITLE
crafting recipes not saving properly

### ISSUE THREAD

**Issue by GeekJokes** [CreativeMD/InGameConfigManager#49]
The custom crafting recipes disappear sometimes after resetting the game... the disabled ones staying disabled though
heres the "latest" file... but what exactly do you look for in it?
[latest-19.1.12-copy.txt](https://github.com/CreativeMD/IGCM/files/2756909/latest-19.1.12-copy.txt)

**Comment by CreativeMD** [comment]
How many recipes have you added? Can you try to reproduce this issue but with only IGCM and CreativeCore installed? If that works can you try to insert all "core" mods (or suspicious mods like vanillatweaks etc.) and see if it still works?

**Comment by Parritoso** [comment]
Excuse me, but I have a similar problem.
When you created a recipe, with an item edited, the NBTags are not saved, they are simply converted into normal items.
I hit the NBT button to set it to On. But it does not work keeps the iron as normal iron, does not save the nbtags.

**Comment by CreativeMD** [comment]
Hit need damage and need nbt and it should work just fine.

EDIT, just saw that I completely missed this issue ... I'm really sorry about that. No idea how this could happen.

**Comment by CreativeMD** [comment]
I will close this issue for now. Just reopen it if the problem still persists.
