### ISSUE TITLE
Hey man this is not a issue

### ISSUE THREAD

**Issue by crunkazcanbe** [CreativeMD/InGameConfigManager#5]
I am going to look at your code ,and edit it some ,but I was wondering if I wanted to add mekanism machine mod support what whould I go about doing within your code . I will do all this myself ,and if I get it working I will submit a pull request if you want ,but could you just give me a hint at where to start at  .Thank you .

**Comment by CreativeMD** [comment]
I'm glad you ask for it. There are no tutorials for this, it think the best way to explain it is to show you an example of it.

Example for a machine:
https://github.com/CreativeMD/RandomAdditions/blob/master/src/main/java/com/creativemd/randomadditions/common/systems/machine/config/RAConfigLoader.java
https://github.com/CreativeMD/RandomAdditions/blob/master/src/main/java/com/creativemd/randomadditions/common/systems/machine/config/RARecipeMachine.java

Example for normal configuration:
https://github.com/CreativeMD/OpticManager/blob/master/src/main/java/com/creativemd/opticmanager/OpticManager.java
https://github.com/CreativeMD/OpticManager/blob/master/src/main/java/com/creativemd/opticmanager/OpticManager.java

Feel free to ask if you have any questions :D

**Comment by CreativeMD** [comment]
Is it enough? If you need any help, feel free to ask
