### ISSUE TITLE
Simple logic gates and wires hidden in jei when crafting module is enabled 

### ISSUE THREAD

**Issue by Trinsdar** [CreativeMD/InGameConfigManager#50]
Charset lib 0.5.5.6
Simple Logic gates and wires 0.5.5.0 mcmultiipart 2.5.3
IGCM 1.2.8
creative core 1.9.41 
jei 4.15.0.268
complex logic 1.4.2

Issue at charset: https://github.com/CharsetMC/Charset/issues/387

**Comment by CreativeMD** [comment]
Sorry but there is no proper way to fix it. I looked at it and it would be a mess. If you don't need to modify the workbench using IGCM I recommend to disable this feature in the config file. That should fix your issue, sorry about that, but the way IGCM is changing recipes is really hacky and I will remove it eventually.
