### ISSUE TITLE
Crashing when im trying to add, edit etc. recipes

### ISSUE THREAD

**Issue by em411** [CreativeMD/InGameConfigManager#51]
https://paste.dimdev.org/xeconivoqi.mccrash

https://paste.dimdev.org/xiwuqiyiqo.mccrash

Client and server side:
- CreativeCore_v1.9.42_mc1.12.2
- IGCM_v1.2.8_mc1.12.2
- ItemPhysic_Full_1.4.19_mc1.12.2
- OpticManager+v1.1.5+mc1.12.2

Everything was fine a few days ago before I updated CC
I can change OpticManager settings without any problem
But when I'm trying change something in crafting, alchemy, furnance or ItemPhysics
It's crashing my game

**Comment by CreativeMD** [comment]
Looks like a brewing recipe is crashing. Either remove it or wait for me to fix it.

**Comment by CreativeMD** [comment]
Does this version fixes it?
https://www.dropbox.com/s/2nqgk9zhc755khd/IGCM_v1.2.9_mc1.12.2.jar?dl=1

**Comment by em411** [comment]
Fixed, thanks :)

**Comment by CreativeMD** [comment]
Nice will upload the update to curseforge.
