### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by SeagalKru** [CreativeMD/InGameConfigManager#52]
Hello!
In one fashion repaired, but in your something broke!

[crash-2019-04-26_09.26.37-server.txt](https://github.com/CreativeMD/IGCM/files/3119977/crash-2019-04-26_09.26.37-server.txt)
[debug.log](https://github.com/CreativeMD/IGCM/files/3119978/debug.log)
[latest.log](https://github.com/CreativeMD/IGCM/files/3119979/latest.log)
[server.log](https://github.com/CreativeMD/IGCM/files/3119980/server.log)

(https://github.com/Laike-Endaril/Dynamic-Stealth/issues/47)

Thank you for your work!

**Comment by CreativeMD** [comment]
Thanks for your report. CreativeCore v1.9.45 should fix it.
