### ISSUE TITLE
Crafting Table Crash

### ISSUE THREAD

**Issue by SeanChengN** [CreativeMD/InGameConfigManager#54]
After starting the game, The first time I put any items into Crafting Table may crash.
If I continue the game, it will return to normal.

https://paste.dimdev.org/xumaxigohu.rb
https://paste.dimdev.org/uzawurubom.rb

Mod Version:
IGCM_v1.2.10
CreativeCore_v1.9.45

**Comment by CreativeMD** [comment]
This issue is caused by FastCraft. Either remove this mod or set enableSwitchButton to false in the config file of IGCM.
