### ISSUE TITLE
1.12.2 Breaks JEI and Craftweaker Recipes.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CreativeMD/InGameConfigManager#55]
So for some reason this mod breaks CraftTweaker and JEI. I Managed to figure this out after 3 hours of testing. Your welcome by the way.

**Comment by P3rf3ctXZer0** [comment]
https://github.com/mezz/JustEnoughItems/issues/1577

**Comment by CreativeMD** [comment]
Crafttweaker and IGCM both manipulate the recipe list. So it is to be expected that it does not work properly. Either remove one of them or disable this feature from IGCM. You can do so by setting enableWorkbench to false (make sure to do it on server and client).

I hope this solves your issue (also added a note to the curseforge page). Unfortunately there is nothing else I can do about it.

**Comment by P3rf3ctXZer0** [comment]
Understood and thank you :D
