### ISSUE TITLE
Recipe Book Recipes Don't Display

### ISSUE THREAD

**Issue by WenXin20** [CreativeMD/InGameConfigManager#56]
Minecart v1.12.2
Forge v14.23.5.2838
IGCM v1.2.10

When the recipe book from the player's inventory or the crafting table's inventory is opened, no recipes will display, unlocked or not.

**Comment by CreativeMD** [comment]
That's a known issue ... unfortunately there is no good way around it. You can set disableWorkbench to true, this should fix it, but also removes the ability to add or disable recipes.
