### ISSUE TITLE
Slow searching speed

### ISSUE THREAD

**Issue by ken1882** [CreativeMD/InGameConfigManager#58]
My server has a total of ~38300 items so far, and when I search in the GUI it's extremely slow whenever I update the search box string (type new text/delete a character, etc.).

I have roughly browsed source and my guess is the search method in the current version is going through all item database with O(n) speed. 

Perhaps build a tweaked suffix tree (for substring searching) after all items are loaded could speed up it.

**Comment by CreativeMD** [comment]
I will close this issue. I will rework IGCM the next months and remove the crafting/ furnace configuration. Sorry, but it's way to hacky and causes many issues.
