### ISSUE TITLE
Recipes are deleted

### ISSUE THREAD

**Issue by Fluttafy** [CreativeMD/InGameConfigManager#59]
There is a problem when you add recipes, most of them are deleted when you restart minecraft.
Most likely the config is overflowing. It removes most of the added craft and any interaction through this mod.
Minecraft version - 1.12.2
Mod version - IGCM_v1.2.10_mc1.12.2

**Comment by CreativeMD** [comment]
I plan to abandon this mod very soon. Sorry but this issue won't be fixed.

**Comment by CreativeMD** [comment]
New version of CreativeCore has been released, IGCM will be abandoned. This repository will be read only.
