### ISSUE TITLE
NEI Support for advanced workbench

### ISSUE THREAD

**Issue by anar4732** [CreativeMD/InGameConfigManager#6]
Hello. We have a problem with  your advanced workbench we are using it in our server modpack and the crafting recipes wont show up on NEI. Is there a possibility you will update the mod to work with the NEI. If it would happen we would really appreciate it. Thank you for the great mod. It made the game much more realistic and fun.

**Comment by CreativeMD** [comment]
Once the update of LittleTiles is out i will start work on it.

**Comment by CreativeMD** [comment]
Is added in v0.1.10
