### ISSUE TITLE
have the same problem again

### ISSUE THREAD

**Issue by anar4732** [CreativeMD/InGameConfigManager#7]
### have the same problem again ###

https://github.com/CreativeMD/CraftingManager/issues/38

**Comment by CreativeMD** [comment]
using cauldron?

**Comment by anar4732** [comment]
@CreativeMD 
no

**Comment by CreativeMD** [comment]
Ok, it's still rather difficult to figure out what is going on. So some recipes are missing, how many recipes you have disable and or added?

**Comment by anar4732** [comment]
Add Ctafting: 50
Disable Crafting: 130
Advanced Crafting: 15
@CreativeMD

**Comment by CreativeMD** [comment]
Should be fixed now, at least the added once
