### ISSUE TITLE
Clients don't see changes

### ISSUE THREAD

**Issue by critterfluffy** [CreativeMD/InGameConfigManager#9]
The mod works great and is nice to have to simplify the process of customizing my server. The only issue I have been seeing is that the client doesn't appear to get the configuration files unless I make a change to the config as an OP while people are logged in. I haven't fully tested this theory but sometimes I seem to see the recipes I created and other times I don't and the only consistent thing I have seen is that the recipes only show up after I have run /CraftingManager once while logged in.

I suspect the config isn't being sent on connection to the client and only when I save it. This is also indicated by no message to the client from Crafting Manager on connection to server but one being sent after finishing using the crafting manager.

Minecraft 1.7.10
Forge 10.13.4.1614
FML 7.10.99.99
InGameConfigManager 0.1.10

NOTE: The recipes work just fine, if I build the thing, it either shows the old result or no result but if I pull the item then I get an overridden result.

Example: I have 9 Endumium from Farlanders create an ender pearl instead of an Endumium block. When I put that recipe in the bench, I see an Endumium block but when I pull it it suddenly becomes a pearl.

**Comment by CreativeMD** [comment]
I'm working on it.

**Comment by CreativeMD** [comment]
Could you try to update to InGameConfigManager 0.1.12?

**Comment by critterfluffy** [comment]
Sorry about the delay. Got lost in my tabs. I am actually doing a server reset this weekend so I will go ahead update the version and let you know. Thanks for the work and hopefully it is working.
